### ISSUE TITLE
Unresolvable dependency resolving [Parameter #0 [ <required> array $annotations ]] in class TheCodingMachine\TDBM\Utils\Annotation\AnnotationParser

### ISSUE THREAD

**Issue by mattsah** [thecodingmachine/tdbm-laravel#4]
Attempting to install in Laravel 5.8 yields error in the title.  Any suggestions?

**Comment by mattsah** [comment]
@moufmouf bump

**Comment by moufmouf** [comment]
Hi @mattsah ,

Sorry for the delay. I confirm I can reproduce the issue.
I'll probably won't have time to dive into it before Monday though...
I'll keep you posted!

**Comment by moufmouf** [comment]
Oh, actually, I just found a work-around.
The problem was that the Laravel-TDBM package targets TDBM 5.0.x and that TDBM 5.1.x was downloaded.
This package will now download TDBM 5.0.x (and therefore work as expected).

Next week, I'll work on updating it to TDBM 5.1. I'll keep the issue open meanwhile.

**Comment by mattsah** [comment]
Much appreciated.  I was looking into it more yesterday and thought it may be somewhat related only cause I noticed a significant number of annotation changes in 5.1.  I'm not normally a Laravel dev, so it was a bit difficult for me to trace down exactly what the problem there was.  This will also be my first project trying TDBM, so I'm on unfamiliar turf on both sides.

Here's to hoping it goes relatively smoothly from here.  **Thanks!**

**Comment by moufmouf** [comment]
Hey @mattsah,

It should be fixed with TDBM 5.1 now. I tagged a new version of the TDBM-Laravel bridge specially tailored for TDBM 5.1.

Hope everything will go well from now. Do not hesitate to open other issues if you find anything strange.

Enjoy!

**Comment by moufmouf** [comment]
Hey @mattsah,

It should be fixed with TDBM 5.1 now. I tagged a new version of the TDBM-Laravel bridge specially tailored for TDBM 5.1.

Hope everything will go well from now. Do not hesitate to open other issues if you find anything strange.

Enjoy!
